import Head from "next/head";
import BreadCrumb from "../components/BreadCrumb/BreadCrumb";
import Categories from "../components/Categories/Categories";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";
import styles from "../styles/Home.module.css";
import { getAll } from "../directus/utils";
import Infos from "../components/Infos/Infos";

const Home = ({ categories, sizes, colors, circles, items }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lujes - Boutique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <BreadCrumb />
      <Categories circles={circles} />
      <Main categories={categories} sizes={sizes} colors={colors} items={items} />
      <Infos />
    </div>
  );
};

export async function getStaticProps() {
  const categories = await getAll("category");
  const sizes = await getAll("size");
  const colors = await getAll("color");
  const circles = await getAll("circle");
  const items = await getAll("item");

  return {
    props: {
      categories,
      sizes,
      colors,
      circles,
      items,
    },
  };
}

export default Home;
